### PR TITLE
Cmapi2 427   doc update

### PR DESCRIPTION
**Pull request by jasonluck**

### CODE REVIEW

**Comment by abhijitvk** [comment]
How long you plan to keep `promotion` branch of `bip-jenkins-lib` repo.  I am hesitant to point to the branch doc link vs the `master` branch

**Comment by jasonluck** [comment]
We are going to have to keep that branch for a while, Openshift is on master and K8s is on promotion branch.

**Comment by abhijitvk** [comment]
can we merge the pipeline documentation .md into `master` and update link here to point to master?

**Comment by jasonluck** [comment]
Sure I can do that.

**Pull request merged**
